// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_Machines_table_to_MainTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Machines_table_to_MainTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201502181823375_added_Machines_table_to_MainTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
