// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Update_databases_layout_touchUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_databases_layout_touchUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201502122132298_Update_databases_layout_touchUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
