// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AdjT_Inst_T : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdjT_Inst_T));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221841145_AdjT_Inst_T"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
